# Generated by Django 4.0 on 2021-12-07 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('plantSeason', models.CharField(max_length=200)),
                ('neededWater', models.CharField(max_length=200)),
                ('price', models.FloatField(default=0)),
                ('placment', models.CharField(max_length=200)),
                ('planttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant', to='myplants_app.planttype')),
            ],
        ),
    ]
