# Generated by Django 4.0 on 2021-12-12 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myplants_app', '0002_seed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planttype',
            options={'ordering': ['-id']},
        ),
    ]
